apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: {{ .Values.app.name }}
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.app.secret.path }}
        metadataPolicy: None
        property: dbpassword
