# Informations du projet
sonar.projectKey=rgpd-saas-angular
sonar.projectName=Saas RGPD Angular
sonar.projectVersion=1.0

# Chemin des sources
sonar.sources=src

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.angular/**,**/*.spec.ts

# Tests
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts



# Couverture
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encodage
sonar.sourceEncoding=UTF-8

# Serveur
sonar.host.url=http://localhost:9000