# Informations du projet
sonar.projectKey=minds-rgpd-front-ng
sonar.projectName=minds-rgpd-front-ng
sonar.projectVersion=1.0

# Chemin des sources
sonar.sources=src

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.angular/**,**/*.spec.ts

# Tests
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Couverture
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encodage
sonar.sourceEncoding=UTF-8
